### PR TITLE
Merge schedule controls

### LINKED ISSUE #377: Schedule settings icon is not centered
## Bug description

I recognized that the gear icon in the schedule detail view is not horizontally centered. This is due to the `margin-right: .2em` that's set on all `.icon::before`.

Image

It's also not vertically centered.

Image

## Reproduce the bug

Go to the schedule list and open any schedule.

## Expected behavior

The icon should be perfectly centered both horizontally and vertically.

### PR DESCRIPTION
**Pull request by nilmerg**
Supposed to be combined with https://github.com/Icinga/ipl-web/pull/333

fixes #377

### CODE REVIEW

File: application/controllers/ScheduleController.php [hunk 1]
```diff
@@ -54,23 +63,46 @@ public function indexAction(): void
...
+                    'mode',
+                    $this->session->get(
+                        'timeline.mode',
+                        ScheduleDetail\Controls::DEFAULT_MODE
+                    )
+                ),
+                'timezone' => $this->params->get(
+                    'display_timezone',
+                    $this->getDisplayTimezoneFromSession($schedule->id, $schedule->timezone)
+                ),
```
Comment (sukhwinder33445) [inline application/controllers/ScheduleController.php]: Please remove `,`.

File: application/controllers/ScheduleController.php [hunk 2]
```diff
@@ -248,55 +280,15 @@ protected function getScheduleTimezone(int $scheduleId): string
...
-                }
-            )
-            ->handleRequest($this->getServerRequest());
-    }
-
     /**
      * Get the display timezone from the session
      *
-     * @param string|null $defaultTimezone
+     * @param string $defaultTimezone
```
Comment (sukhwinder33445) [inline application/controllers/ScheduleController.php]: Param `$scheduleId` is missing here.

File: library/Notifications/Widget/Detail/ScheduleDetail/Controls.php [hunk 3]
```diff
@@ -24,47 +30,103 @@ class Controls extends Form
...
 
     /**
-     * Get the number of days the user wants to see
+     * Get the timezone the user wants to see the schedule in
      *
-     * @return int
+     * @return string
      */
-    public function getNumberOfDays(): int
+    public function getTimezone(): string
```
Comment (sukhwinder33445) [inline library/Notifications/Widget/Detail/ScheduleDetail/Controls.php]: The param `$this->defaultTimezone` can be null.

File: library/Notifications/Widget/Detail/ScheduleDetail/Controls.php [hunk 4]
```diff
@@ -24,47 +30,103 @@ class Controls extends Form
...
+                'notifications/suggest/timezone',
+                ['showCompact' => true, '_disableLayout' => 1, 'default' => $this->defaultTimezone]
+            ),
+            'decorators' => [
+                'Label' => [
+                    'name' => 'Label',
+                    'options' => ['uniqueName' => fn(string $name) => Icinga::app()->getRequest()->protectId($name)]
+                ]
+            ],
+            'validators' => [new CallbackValidator(function ($value, $validator) {
```
Comment (sukhwinder33445) [inline library/Notifications/Widget/Detail/ScheduleDetail/Controls.php]: Param `$validator` is unused, please remove.

**Review by sukhwinder33445 — CHANGES_REQUESTED** [review]
When I manually add the `display_timezone` in the URL, it isn’t cached. However, if I then change the mode in the UI, the timezone is cached. Is this the intended behavior?

**Review by sukhwinder33445 — APPROVED** [review]
